### ISSUE TITLE
chatunitest IDEA plugin GPT connection error

### ISSUE THREAD

**Issue by Pallav-552** [ZJU-ACES-ISE/chatunitest_plugin_idea#2]
IntelliJ IDEA 2023.1.5 (Community Edition)
Build #IC-231.9392.1, built on July 25, 2023
Java version : 11

![Selection_093](https://github.com/ZJU-ACES-ISE/ChatUniTest_IDEA_Plugin/assets/26543276/a42daa9d-050e-40af-9424-c5c6fac72f50)

As per the tutorial vedio [https://www.youtube.com/watch?v=NWfNkDJcJGE](url) , shows 3 info
1) openAI keys
2) host(127.0.0.1)
3) port(10809)

1 thing I am not clear is why we were giving local host for chatGPT connection.

**Comment by NCCurry30** [comment]
Hello, normally, Host and Port need to be configured only when a proxy is used. If no proxy is used, these two configurations can be left empty.

**Comment by Pallav-552** [comment]
Ok got it . Thanks.
